const data = {
  products: [
    {
      id: 1,
      name: "Sukienka BALLOON LATTE",
      category: "sukienki",
      image: ["/img/sukienki/sukienka_balloon_latte1.jpg"],
      price: 229,
      sizes: {},
      countInStock: 3,
      description: "high quality product",
      isNew: true,
      isBestseller: true,
    },
    {
      id: 2,
      name: "Sukienka BALLOON BLACK",
      category: "sukienki",
      image: ["/img/sukienki/sukienka_balloon_black1.jpg"],
      price: 229,
      sizes: {},
      countInStock: 2,
      description: "high quality product",
      isNew: true,
      isBestseller: true,
    },
    {
      id: 3,
      name: "Bluza BABY BLUE",
      category: "bluzy",
      image: ["/img/bluzy/bluza_baby_blue1.jpg"],
      price: 259,
      sizes: {},
      countInStock: 3,
      description: "high quality product",
      isNew: true,
      isBestseller: true,
    },
    {
      id: 4,
      name: "Bluza CINNAMON",
      category: "bluzy",
      image: ["/img/bluzy/bluza_cinnamon1.jpg"],
      price: 259,
      sizes: {},
      countInStock: 5,
      description: "high quality product",
      isNew: true,
      isBestseller: true,
    },
    {
      id: 5,
      name: "Spódnica Dresowa NUDE",
      category: "spodnice",
      image: ["/img/spodnice/spodnica_dresowa_nude1.jpg"],
      price: 169,
      sizes: {},
      countInStock: 5,
      description: "high quality product",
      isNew: true,
      isBestseller: true,
    },
    {
      id: 6,
      name: "Spodnie Dresowe CINNAMON",
      category: "spodnie",
      image: ["/img/spodnie/spodnie_dresowe_cinnamon1.jpg"],
      price: 199,
      sizes: {},
      countInStock: 5,
      description: "high quality product",
      isNew: true,
      isBestseller: true,
    },
    {
      id: 7,
      name: "Komplet Dresowy BABY BLUE",
      category: "komplety",
      image: ["/img/komplety/komplet_dresowy_baby_blue1.jpg"],
      price: 399,
      sizes: {},
      countInStock: 5,
      description: "high quality product",
      isNew: true,
      isBestseller: true,
    },
    {
      id: 8,
      name: "Komplet Dresowy CINNAMON",
      category: "komplety",
      image: ["/img/komplety/komplet_dresowy_cinnamon1.jpg"],
      price: 429,
      sizes: {},
      countInStock: 5,
      description: "high quality product",
      isNew: true,
      isBestseller: true,
    },
  ],
  instagram: [
    {
      image: "/img/bluzy/bluza_baby_blue1.jpg",
      url: "https://www.instagram.com/p/CXDsHsJq9Kc/",
    },
    {
      image: "/img/spodnie/spodnie_dresowe_cinnamon1.jpg",
      url: "https://www.instagram.com/p/CXDrnXPqX0n/",
    },
    {
      image: "/img/komplety/komplet_dresowy_cinnamon1.jpg",
      url: "https://www.instagram.com/p/CXCXe-NKu2f/",
    },
    {
      image: "/img/sukienki/sukienka_balloon_latte1.jpg",
      url: "https://www.instagram.com/p/CW4CwHCq0Ox/",
    },
    {
      image: "/img/spodnice/spodnica_dresowa_nude1.jpg",
      url: "https://www.instagram.com/p/CXDtsMYKZyP/",
    },
  ],
};

export default data;
