const data = {
  products: [
    {
      _id: "1",
      category: "sukienki",
      name: "Sukienka BALLOON LATTE",
      price: 229,
      image: [
        "/img/sukienki/sukienka_balloon_latte1.jpg",
        "/img/sukienki/sukienka_balloon_latte1.jpg",
        "/img/sukienki/sukienka_balloon_latte1.jpg",
        "/img/sukienki/sukienka_balloon_latte1.jpg",
      ],
      color: "#AF9479",
      sizes: [
        { size: "XS", countInStock: 2 },
        { size: "S/M", countInStock: 5 },
        { size: "L/XL", countInStock: 0 },
      ],
      description: "high quality product",
      dimensions: 1,
      isNew: true,
      isBestseller: true,
    },
    {
      _id: "2",
      category: "sukienki",
      name: "Sukienka BALLOON BLACK",
      price: 229,
      image: [
        "/img/sukienki/sukienka_balloon_black1.jpg",
        "/img/sukienki/sukienka_balloon_black1.jpg",
        "/img/sukienki/sukienka_balloon_black1.jpg",
      ],
      color: "#040404",
      sizes: [
        { size: "XS", countInStock: 2 },
        { size: "S/M", countInStock: 5 },
        { size: "L/XL", countInStock: 1 },
      ],
      description: "high quality product",
      dimensions: 1,
      isNew: true,
      isBestseller: false,
    },
    {
      _id: "3",
      category: "bluzy",
      name: "Bluza BABY BLUE",
      price: 259,
      image: [
        "/img/bluzy/bluza_baby_blue1.jpg",
        "/img/bluzy/bluza_baby_blue1.jpg",
      ],
      color: "#60ACD8",
      sizes: [
        { size: "XS-M", countInStock: 2 },
        { size: "M-XL", countInStock: 5 },
      ],
      description: "high quality product",
      dimensions: 1,
      isNew: true,
      isBestseller: true,
    },
    {
      _id: "4",
      category: "bluzy",
      name: "Bluza CINNAMON",
      price: 259,
      image: [
        "/img/bluzy/bluza_cinnamon1.jpg",
        "/img/bluzy/bluza_cinnamon1.jpg",
        "/img/bluzy/bluza_cinnamon1.jpg",
        "/img/bluzy/bluza_cinnamon1.jpg",
      ],
      color: "#3C232A",
      sizes: [
        { size: "XS-M", countInStock: 2 },
        { size: "M-XL", countInStock: 5 },
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur consequatur odio, similique quo facilis, ipsum deserunt quam quibusdam nulla labore quos cum veritatis dolore temporibus dicta, iure maxime. Inventore, quisquam.",
      dimensions: 1,
      isNew: true,
      isBestseller: false,
    },
    {
      _id: "5",
      category: "spodnice",
      name: "Spódnica Dresowa NUDE",
      price: 169,
      image: [
        "/img/spodnice/spodnica_dresowa_nude1.jpg",
        "/img/spodnice/spodnica_dresowa_nude1.jpg",
        "/img/spodnice/spodnica_dresowa_nude1.jpg",
        "/img/spodnice/spodnica_dresowa_nude1.jpg",
      ],
      color: "#D8D4D3",
      sizes: [
        { size: "XS", countInStock: 2 },
        { size: "S/M", countInStock: 5 },
        { size: "L/XL", countInStock: 1 },
      ],
      description: "high quality product",
      dimensions: 1,
      isNew: true,
      isBestseller: true,
    },
    {
      _id: "6",
      category: "spodnie",
      name: "Spodnie Dresowe CINNAMON",
      price: 199,
      image: [
        "/img/spodnie/spodnie_dresowe_cinnamon1.jpg",
        "/img/spodnie/spodnie_dresowe_cinnamon1.jpg",
        "/img/spodnie/spodnie_dresowe_cinnamon1.jpg",
        "/img/spodnie/spodnie_dresowe_cinnamon1.jpg",
      ],
      color: "#3C232A",
      sizes: [
        { size: "XS", countInStock: 2 },
        { size: "S/M", countInStock: 5 },
        { size: "L/XL", countInStock: 1 },
      ],
      description: "high quality product",
      dimensions: 1,
      isNew: true,
      isBestseller: false,
    },
  ],
  instagram: [
    {
      _id: 1,
      image: "/img/bluzy/bluza_baby_blue1.jpg",
      url: "https://www.instagram.com/p/CXDsHsJq9Kc/",
    },
    {
      _id: 2,
      image: "/img/spodnie/spodnie_dresowe_cinnamon1.jpg",
      url: "https://www.instagram.com/p/CXDrnXPqX0n/",
    },
    {
      _id: 3,
      image: "/img/komplety/komplet_dresowy_cinnamon1.jpg",
      url: "https://www.instagram.com/p/CXCXe-NKu2f/",
    },
    {
      _id: 4,
      image: "/img/sukienki/sukienka_balloon_latte1.jpg",
      url: "https://www.instagram.com/p/CW4CwHCq0Ox/",
    },
    {
      _id: 5,
      image: "/img/spodnice/spodnica_dresowa_nude1.jpg",
      url: "https://www.instagram.com/p/CXDtsMYKZyP/",
    },
  ],
};

export default data;
